# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AZLoop.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxDataValues = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDataValues.setGeometry(QtCore.QRect(380, 10, 361, 291))
        self.groupBoxDataValues.setObjectName("groupBoxDataValues")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBoxDataValues)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 331, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditTargetSpeed = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditTargetSpeed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditTargetSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTargetSpeed.setObjectName("lineEditTargetSpeed")
        self.gridLayout.addWidget(self.lineEditTargetSpeed, 0, 4, 1, 1)
        self.lineEditInTime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditInTime.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditInTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditInTime.setObjectName("lineEditInTime")
        self.gridLayout.addWidget(self.lineEditInTime, 1, 4, 1, 1)
        self.labelTargetSpeed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelTargetSpeed.setObjectName("labelTargetSpeed")
        self.gridLayout.addWidget(self.labelTargetSpeed, 0, 1, 1, 1)
        self.labelInTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelInTime.setObjectName("labelInTime")
        self.gridLayout.addWidget(self.labelInTime, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(4, 2)
        self.pushButtonPrepDataValues = QtWidgets.QPushButton(self.groupBoxDataValues)
        self.pushButtonPrepDataValues.setGeometry(QtCore.QRect(230, 130, 121, 23))
        self.pushButtonPrepDataValues.setObjectName("pushButtonPrepDataValues")
        self.groupBoxPreppedDataValues = QtWidgets.QGroupBox(self.groupBoxDataValues)
        self.groupBoxPreppedDataValues.setGeometry(QtCore.QRect(10, 140, 341, 141))
        self.groupBoxPreppedDataValues.setObjectName("groupBoxPreppedDataValues")
        self.labelPreppedTargetSpeedLabel = QtWidgets.QLabel(self.groupBoxPreppedDataValues)
        self.labelPreppedTargetSpeedLabel.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.labelPreppedTargetSpeedLabel.setObjectName("labelPreppedTargetSpeedLabel")
        self.labelPreppedInTimeLabel = QtWidgets.QLabel(self.groupBoxPreppedDataValues)
        self.labelPreppedInTimeLabel.setGeometry(QtCore.QRect(10, 70, 121, 20))
        self.labelPreppedInTimeLabel.setObjectName("labelPreppedInTimeLabel")
        self.labelPreppedTargetSpeed = QtWidgets.QLabel(self.groupBoxPreppedDataValues)
        self.labelPreppedTargetSpeed.setGeometry(QtCore.QRect(250, 40, 81, 21))
        self.labelPreppedTargetSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPreppedTargetSpeed.setObjectName("labelPreppedTargetSpeed")
        self.labelPreppedInTime = QtWidgets.QLabel(self.groupBoxPreppedDataValues)
        self.labelPreppedInTime.setGeometry(QtCore.QRect(250, 60, 81, 21))
        self.labelPreppedInTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPreppedInTime.setObjectName("labelPreppedInTime")
        self.groupBoxSettings = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSettings.setGeometry(QtCore.QRect(20, 10, 341, 291))
        self.groupBoxSettings.setObjectName("groupBoxSettings")
        self.comboBoxCurveChoices = QtWidgets.QComboBox(self.groupBoxSettings)
        self.comboBoxCurveChoices.setGeometry(QtCore.QRect(20, 50, 301, 21))
        self.comboBoxCurveChoices.setObjectName("comboBoxCurveChoices")
        self.comboBoxCurveChoices.addItem("")
        self.groupBoxPreppedSettings = QtWidgets.QGroupBox(self.groupBoxSettings)
        self.groupBoxPreppedSettings.setGeometry(QtCore.QRect(10, 140, 321, 141))
        self.groupBoxPreppedSettings.setObjectName("groupBoxPreppedSettings")
        self.labelPreppedCurveModeLabel = QtWidgets.QLabel(self.groupBoxPreppedSettings)
        self.labelPreppedCurveModeLabel.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.labelPreppedCurveModeLabel.setObjectName("labelPreppedCurveModeLabel")
        self.labelPreppedCurveMode = QtWidgets.QLabel(self.groupBoxPreppedSettings)
        self.labelPreppedCurveMode.setGeometry(QtCore.QRect(150, 30, 161, 20))
        self.labelPreppedCurveMode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPreppedCurveMode.setObjectName("labelPreppedCurveMode")
        self.pushButtonPrepSettings = QtWidgets.QPushButton(self.groupBoxSettings)
        self.pushButtonPrepSettings.setGeometry(QtCore.QRect(220, 120, 111, 23))
        self.pushButtonPrepSettings.setObjectName("pushButtonPrepSettings")
        self.radioButtonSendConfirm = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonSendConfirm.setGeometry(QtCore.QRect(620, 410, 121, 17))
        self.radioButtonSendConfirm.setObjectName("radioButtonSendConfirm")
        self.pushButtonHaltCommand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHaltCommand.setGeometry(QtCore.QRect(620, 440, 111, 51))
        self.pushButtonHaltCommand.setObjectName("pushButtonHaltCommand")
        self.groupBoxDisplay = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDisplay.setGeometry(QtCore.QRect(20, 310, 591, 201))
        self.groupBoxDisplay.setObjectName("groupBoxDisplay")
        self.textBrowserDisplay = QtWidgets.QTextBrowser(self.groupBoxDisplay)
        self.textBrowserDisplay.setGeometry(QtCore.QRect(10, 30, 571, 161))
        self.textBrowserDisplay.setObjectName("textBrowserDisplay")
        self.pushButtonSendCommand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSendCommand.setGeometry(QtCore.QRect(620, 340, 111, 51))
        self.pushButtonSendCommand.setObjectName("pushButtonSendCommand")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 758, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHi_D = QtWidgets.QAction(MainWindow)
        self.actionHi_D.setObjectName("actionHi_D")
        self.menuFile.addAction(self.actionHi_D)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AZLoop"))
        self.groupBoxDataValues.setTitle(_translate("MainWindow", "Data Values"))
        self.labelTargetSpeed.setText(_translate("MainWindow", "Target Speed"))
        self.labelInTime.setText(_translate("MainWindow", "In time (seconds)"))
        self.pushButtonPrepDataValues.setText(_translate("MainWindow", "Prep Data Values"))
        self.groupBoxPreppedDataValues.setTitle(_translate("MainWindow", "Prepped Data Values"))
        self.labelPreppedTargetSpeedLabel.setText(_translate("MainWindow", "Target Speed"))
        self.labelPreppedInTimeLabel.setText(_translate("MainWindow", "In time (seconds)"))
        self.labelPreppedTargetSpeed.setText(_translate("MainWindow", "TextLabel"))
        self.labelPreppedInTime.setText(_translate("MainWindow", "TextLabel"))
        self.groupBoxSettings.setTitle(_translate("MainWindow", "Settings"))
        self.comboBoxCurveChoices.setItemText(0, _translate("MainWindow", "Linear Curve"))
        self.groupBoxPreppedSettings.setTitle(_translate("MainWindow", "Prepped Settings"))
        self.labelPreppedCurveModeLabel.setText(_translate("MainWindow", "Curve Mode:"))
        self.labelPreppedCurveMode.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonPrepSettings.setText(_translate("MainWindow", "Prep Settings"))
        self.radioButtonSendConfirm.setText(_translate("MainWindow", "Send Confirm"))
        self.pushButtonHaltCommand.setText(_translate("MainWindow", "Halt Command"))
        self.groupBoxDisplay.setTitle(_translate("MainWindow", "Display"))
        self.pushButtonSendCommand.setText(_translate("MainWindow", "Send Command"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionHi_D.setText(_translate("MainWindow", "Hi :D"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
